name: Reusable job

on:
  workflow_call:
    inputs:
      environment-name:
        required: false
        type: string
        default: github-pages # only this one in use rn

# TODO: decompose to "build" and "deploy" steps
jobs:
  deploy:
    # do not deploy if [skip-ci] is in a commit message
    if: |
      !contains(github.event.head_commit.message, '[skip-ci]')
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      deployments: write
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'
          registry-url: 'https://registry.npmjs.org'

      - name: Enforce npm version 8.3.0
        run: |
          npm install -g npm@8.3.0
          echo "Updated npm version: $(npm --version)"
    
      # react-snap has build-in "npm —Åi" and "npm run build"
      - name: Server-side render by crawler
        uses: brycedorn/react-snap-action@v1.0.2

      - name: Copy HTML gallery
        run: |
          npm run build:html-gallery 
          npm run fix-react-snap

      - name: Create Deployment Entry
        id: deployment
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          environment-url: http://shapkarin.me

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        id: actions-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          environment: ${{ inputs.environment-name }}

      - name: Update Deployment Status
        if: always()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ steps.deployment.outputs.environment }}
          state: ${{ job.status == 'success' && 'success' || 'failure' }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          environment-url: ${{ steps.deployment.outputs.deployment-url }}
          # TODO: if inputs == onSchedule then write: autodeployed and current date
          description: "Completed ${{ job.status == 'success' && 'successful' || 'failed' }} deploy to gh-pages"

      - run: printf Deployed!
