name: Deploy on changes in main

on:
  push:
    branches: [ "main" ]

jobs:
  call-deploy:
    uses: ./.github/workflows/job.yml
    with:
      environment-name: github-pages
      deployment-description: "Deploy on main changes. ${{ github.ref_name }}"
